config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   root 'homes#top'
  get "home/about" => "homes#about"
  resources :users, only: [:show, :index, :edit]

  #guestuser機能
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :books, only: [:show, :index, :edit, :create, :new] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  def favorited_by?(user)
   favorites.where(user_id: user.id).exists?
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@guest') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to book_path(@book.id)
  end

  def show
    @book = Book.find(params[:id])
    @book_user = @book.user
    @book_new = Book.new
    @comment = Comment.new
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = User.find(current_user.id)
  end

  def edit

  end

  private

  def book_params
  params.require(:book).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_user = @book.user
    @comment = current_user.comments.new(comment_params)
    @comment.book_id = @book.id
    @comment.save
    flash[:notice] = '投稿にコメントしました。'
  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_user = @book.user
    @comment = @book.comments.find(params[:id])
    @comment.destroy
    flash[:notice] = 'コメントを削除しました。'
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    favorite = Favorite.new(user_id: current_user.id, book_id: params[:book_id])
    favorite.save
    flash[:notice] = '投稿に「いいね！」しました。'
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    favorite = Favorite.find_by(user_id: current_user.id, book_id: params[:book_id])
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]
  def new
    @user = User.new
  end

  def create
  @user = User.new(user_params)
  end

  def show
  end

  def index

  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def user_params
  params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model:book do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<h2>Books</h2>
<table class="table table-hover">
  <thead>
    <tr class="text-light">
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tboody>
    <% books.each do |book| %>
    <tr class="text-light">
      <td><%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image, size:"50x50" %>
            <%= book.user.name %>
          <% end %>
      </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
      <td>コメント数: <%= book.comments.count %></td>
      <td id="btn_<%= book.id %>">
        　<% unless user_signed_in? && current_user.id == book.user_id %>
          <!-- 自分の投稿にはいいねができない -->
      　　　　<%= render "favorites/btn", book: book %> 
    　   　 <% end %>
    　</td>
    </tr>
    <% end %>
  </tboody>
</table>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%=render 'users/info', user: current_user %>
      <%=render 'form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <%=render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/nagao_cake.html.erb
<div class="col-sm-3 col-md-3 col-lg-3 px-3 offset-1">
      <p>請求情報</p>
    <div class="col-3 px-3 mt-3">
      <p><strong>請求情報</strong></p>
      <table class="table table-bordered">
        <tr><th class="table-active">送料</th><td>800</td></tr>
        <tr><th class="table-active">商品合計</th><td><%= @order.total_price - 800 %></td></tr>
        <tr><th class="table-active">請求合計</th><td><%= @order.total_price %></td></tr>
        <tr><th class="table-active">商品合計</th><td><%= (@order.total_price - @shipping_cost).to_s(:delimited) %></td></tr>
        <tr><th class="table-active">請求合計</th><td><%= @order.total_price.to_s(:delimited) %></td></tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8 col-md-8 col-lg-8 px-8">
      <p>注文内容</p>
      <p><strong>注文内容</strong></p>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="table-active" style="width:60%">商品</th>
            <th class="table-active" style="width:20%">単価（税込み）</th>
            <th class="table-active" style="width:20%">単価（税込）</th>
            <th class="table-active" style="width:10%">個数</th>
            <th class="table-active" style="width:10%">小計</th>
          </tr>
@@ -34,9 +44,9 @@
        <% @order.order_items.each do |order_item| %>
          <tr>
            <td style="word-break:break-all"><%= order_item.item.name %></td>
            <td><%= order_item.price %></td>
            <td><%= order_item.price.to_s(:delimited) %></td>
            <td><%= order_item.amount %></td>
            <td><%= order_item.amount * order_item.price %></td>
            <td><%= (order_item.amount * order_item.price).to_s(:delimited) %></td>
          </tr>
        <% end %>
        </tbody>
 2  
app/views/public/orders/thanks.html.erb
Viewed
@@ -1,5 +1,5 @@
<div class = "container">
  <div class="row">
  <div class="row pt-5 mt-5">
    <div class = "mx-auto pt-5 mt-5">
      <h2>ご注文ありがとうございました!</h2>
    </div>
  10  
app/views/public/registration

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%=render 'users/info', user: @book_user %>
      <%=render 'form', book: @book_new  %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2 class="mt-3">Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td><%= link_to(@book_user) do %>
                <%= image_tag @book.user.get_profile_image, size:'100x100' %><br>
                <%= @book.user.name %>
                <% end %>
            </td>
            <td><%= link_to @book.title, @book %></td>
            <td><%= @book.body %></td>
            <td id="comments_counter"><%= render 'comments/counter', book: @book %></td>
            <td id="btn_<%=@book.id %>">
                  <%= render "favorites/btn", book: @book %>
            </td>
          </tr>
        </tbody>
      </table>
      <div id="comments_index"><%= render "comments/index", book: @book, user: @book_user %></div>
      <div><%= render "comments/form", book: @book, comment: @comment %></div>
    </div>
  </div>
</div>

app/views/comments/_counter.html.erb
コメント数: <%= book.comments.count %>

app/views/comments/_form.html.erb
<%= form_with(model:[book, comment], local: false) do |f| %>
  <%= f.text_area :comment, row: '5', placeholder: "コメント入力", class: "w-100 comment_form" %>
  <%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/comments/_index.html.erb
<table>
  <tbody>
      <% book.comments.each do |comment| %>
      <tr>

        <td>
          <%= link_to user_path(user) do %>
            <%= image_tag comment.user.get_profile_image, size: "100x100" %><br>
            <%= comment.user.name %>
          <% end %>
        </td>
        <td><%= comment.comment %></td>
        <td>
          <% if comment.user == current_user %>
            <%= link_to "削除", book_comment_path(comment.book_id, comment.id), method: :delete, remote: true,class: "btn btn-sm btn-danger pull-right", data: {confirm: "本当に削除しますか？"} %>
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/comments/create.js.erb
console.log ('create.js.erb')

$('#comments_counter').html("<%=j(render 'comments/counter', book: @book) %>");
$('#comments_index').html("<%= j(render "comments/index", book: @book, user: @book_user) %>");
$('.comment_form').val("");

app/views/comments/destroy.js.erb
console.log ('destroy.js.erb')

$('#comments_counter').html("<%=j(render 'comments/counter', book: @book) %>");
$('#comments_index').html("<%= j(render "comments/index", book: @book, user: @book_user) %>");
$('.comment_form').val("");

app/views/favorites/_btn.html.erb
  <% if book.favorited_by?(current_user) %>
    <!-- 一致するレコードが存在する＝すでにいいね済みの場合はdestroyアクションへ -->
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
      <%= book.favorites.count %> 
    <% end %>
  <% else %>
    <!-- 一致するレコードが存在しない＝まだいいねしていない場合はcreateアクションへ -->
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      <i class="fas fa-heart" aria-hidden="true"></i>
      <%= book.favorites.count %>
    <% end %>
  <% end %>

app/views/favorites/create.js.erb
console.log ('create.js.erb')
$("#btn_<%= @book.id %>").html("<%= j(render 'favorites/btn', book: @book) %>");

app/views/favorites/destroy.js.erb
console.log('destroy.js.erb')
$("#btn_<%= @book.id %>").html("<%= j(render 'favorites/btn', book: @book) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto ">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
        <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to 'Sign up',new_user_registration_path, class: "btn btn-success btn-sm btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "btn btn-danger btn-sm btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-white">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag("maru.jpeg", size: "160x80")%></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user),class: 'nav-link ' do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path,class: 'nav-link text-dark' do %>
                  <i class="fas fa-users"></i> Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path,class: 'nav-link text-dark' do %>
                  <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-dark' do %>
                  <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path,class: 'nav-link text-dark' do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to home_about_path,class: 'nav-link text-dark' do %>
                  <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path,class: 'nav-link text-dark' do %>
                  <i class="fas fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path,class: 'nav-link text-dark' do %>
                  <i class="fas fa-sign-in-alt"></i> Log in
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="text-center  alert-success"><%= flash[:notice] %></div>
      <div class="text-center  alert-danger"><%= flash[:danger] %></div>
    <%= yield %>
    </main>
    <footer>
      <div class="container mt-8">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_info.html.erb
<h2>User info</h2>
<table class="table">
  <tbody>
    <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
      <th>name</th>
      <th><%= current_user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= current_user.introduction %></th>
    </tr>
  </tbody>
</table>

<% if user.name != "guestuser" %>
<div class="row">
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Users Edit</h1>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>